AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - '.bundle/**/*'

Rails:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: leading

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - guard
    - define
    - feature
    - specify
    - scenario
    - include_context

Naming/FileName:
  Exclude:
    - Capfile
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - Guardfile
    - Procfile

Metrics/LineLength:
  Max: 100

Rails/Delegate:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic
  ProceduralMethods:
    - benchmark
    - bm
    - create
    - each_with_object
    - each_key
    - measure
    - new
    - tap
    - with_object
    - Form
  FunctionalMethods:
    - let
    - let!
    - subject
    - watch
    - map
    - map!
    - attribute
  IgnoredMethods:
    - lambda
    - proc
    - specify
    - it
    - try
    - compose
  Exclude:
    - 'spec/factories/*.rb'
    - 'spec/support/factory*.rb'
    - '**/*.builder'

# Style/ColonMethodCall:
#   Enabled: false

Style/Documentation:
  Enabled: false
  Exclude:
    - 'app/**/*'

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/StringLiterals:
  EnforcedStyle: double_quotes
